### ISSUE TITLE
Study existing MapShed code (Ghost Wolfe)

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/gwlf-e#2]
MapShed code is in two parts:

A model back-end which actually executes the MapShed model, reading in the GMS file generated by the GIS Frontend. This is written in VB6. More details are available here: https://github.com/azavea/civic-apps/issues/82

Study it prior to beginning the port.

**Comment by caseypt** [comment]
I've gone through all of the .bas files and written a short description of what I think they are doing. You can find that here: https://docs.google.com/spreadsheets/d/1gwdpuM5E1fO1XYhjoP8_ypFb7xnfR7WZU6Ndt-3sz-4/edit.

The files I analyzed are located at smb://fileshare.internal.azavea.com/projects/Stroud_ModelMyWatershed/downloads/mapshed/2014_11_18_MapShed_ModelCode.zip

In that zip file, the files in RunFiles/Output/Images give an idea of what the output looks like and how it can be displayed.
