### ISSUE TITLE
Port PrelimQualCalculations

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/gwlf-e#26]
There are a set of variables, listed below, that are initialized in this module that we need.

```
ImpervAccum
PervAccum
LuLoad
LuDisLoad
Erosiv
QrunI
QrunP
WashPerv
NetDisLoad
UrbanQTotal
```

Consider porting over the whole `ReDimRunQualVars` routine even if we don't need it all. It's not always easy to tell when manipulation of variables effects other variables.

**Comment by kdeloach** [comment]
I'll move these variable declarations (and any other missing variables from this module) to the parser so everything is initialized in a single place.

**Comment by kdeloach** [comment]
Closing for now.
