### ISSUE TITLE
Output sediment loading variables

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/gwlf-e#39]
Details TBD.

**Comment by ajrobbins** [comment]
BME recommends that the "Water Quality" tab for MapShed's model output show the following information:

Total Area of Watershed (ha):
Mean Annual Flow (m^3):
Mean Annual flow (cfs (cubic ft per second)):

Sources | Sediment | Total Nitrogen | Total Phosphorus |
----------- | ------------- | ------------------ | ----------------------- 
Hay/Pasture | xxxx | xxxx | xxxx
Cropland | xxxx | xxxx | xxxx
Wooded Areas | xxxx | xxxx | xxxx
Wetlands | xxxx | xxxx | xxxx
Open Land | xxxx | xxxx | xxxx
Barren Areas | xxxx | xxxx | xxxx
Low-Density Mixed | xxxx | xxxx | xxxx
Medium-Density Mixed | xxxx | xxxx | xxxx
High-Density Mixed | xxxx | xxxx | xxxx
Other Upland Areas | xxxx | xxxx | xxxx
Farm Animals | xxxx | xxxx | xxxx
Stream Bank Erosion | xxxx | xxxx | xxxx
Subsurface Flow | xxxx | xxxx | xxxx
Point Sources | xxxx | xxxx | xxxx
Septic Systems | xxxx | xxxx | xxxx
**Total Loads (kg)**  | **xxxx** | **xxxx** | **xxxx**
**Loading Rates (kg/ha)**  | **xxxx** | **xxxx** | **xxxx**
**Mean Annual Concentration (mg/l)**  | **xxxx** | **xxxx** | **xxxx**
**Mean Low-Flow Concentration (mg/l)**  | **xxxx** | **xxxx** | **xxxx**

**Comment by mmcfarland** [comment]
This is taken from a screen in VB GWLF-E, and I believe is the next chunk of output after hydrology stuff in the output sum dat file.

**Comment by lewfish** [comment]
So this is to just get these variables into the output JSON and then show these in the UI as a table?

**Comment by mmcfarland** [comment]
Correct.  The VB code will need to get ported and added to the JSON output.  It doesn't include the UI, unless the former task doesn't take very long.  We can have a separate card for the UI.  I thought there would be monthly average values to plot as well, but I don't see it in the above table.  I'll do some digging.

**Comment by mmcfarland** [comment]
Yeah, let's just stick with the table as reported above - no graph.  But again, this card is meant for adding loading values to the model output.

**Comment by kdeloach** [comment]
> Loading Rates = Total Loads / Total Area

**Comment by ajrobbins** [comment]
Further information on the source of Mean Annual Flow, Loading Rates, Mean Annual Concentration, and Mean Low-Flow Concentration is on the Google Drive: 
https://drive.google.com/open?id=0B0hs2mX4ApaLYXBPS2RwTG1JZ1FOZ2UybXpBTEdaU2VaWVdz
https://drive.google.com/open?id=0B0hs2mX4ApaLc0xxY2s1LUV1ZG9LSlo0MUhLZUkyLTdleDlF

**Comment by ajrobbins** [comment]
From BME: The "Subsurface Flow" output in the table corresponds to the "Groundwater" output from MapShed. cc @kdeloach 
![screen shot 2016-05-04 at 2 24 47 pm](https://cloud.githubusercontent.com/assets/12868342/15024725/162f7c7c-1204-11e6-9932-69bae361d9e4.png)

**Comment by ajrobbins** [comment]
When this table gets put into the UI, we should use NLCD land use names as mapped here: https://docs.google.com/spreadsheets/d/1XTJVQI2sSVKnS5U5hsJOq0eznaCULKPgo3Uw4fUzzQQ/edit#gid=0
