### ISSUE TITLE
Output should be numeric, not strings

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/gwlf-e#41]
Currently the output of gwlfe.py is a json document with hydrologic measures as string vlaue.  These should be numeric.

**Comment by kdeloach** [comment]
We should use `round` instead of `format` here: https://github.com/WikiWatershed/gwlf-e/blob/develop/gwlfe/WriteOutputFiles.py#L722

**Comment by kdeloach** [comment]
Fixed by 9dfbcc680065efb4d2170d42621c18ecd9c8eea8.
