### ISSUE TITLE
Remove debug logging

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/gwlf-e#54]
The existing debug logging showing modules called isn't useful and is verbose when viewed on stdout or celery logs.

**Comment by kdeloach** [comment]
The logging should only appear if the log level is set to `DEBUG`. Setting the log level to `INFO` or higher in MMW should resolve this.

**Comment by mmcfarland** [comment]
Perhaps we could update the contents of the log, I just don't think seeing `CalcCN` so many times in a row will help us track anything down.
