### ISSUE TITLE
Stub out model workflow

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/gwlf-e#6]
Based on the workflow laid out in AllInOneTest.bas, stub out a workflow the model run. 

Note that the code in this file may not include the complete model run. There are some modules that are not referenced from this module.

**Comment by mmcfarland** [comment]
I looked into it  and I don't think AllInOneTest.bas is the main run file section.

Check GWLF-E.frm at line 774 for the click handler for the "run" button.  Specifically line 1181-1460 looks like the actual model running code.

**Comment by caseypt** [comment]
Thanks @mmcfarland. I'll switch over to porting that section of code over instead of AllInOneTest.Bas. The code is very similar, but it does contain some small differences.
