### ISSUE TITLE
Port over global variables

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/gwlf-e#7]
There are a lot of global variables used in the current version of the model that should be brought over and refactored into a more manageable structure (like a dict). They mostly (but not all) can be seen in PublicVariables.bas.

**Comment by rajadain** [comment]
* Setup a global object for values from the GMS file in addition to the global variables defined in PublicVariables.bas
 * Add at least two modules that can communicate via the shared globals

**Comment by mmcfarland** [comment]
For global variables, see comment here https://github.com/WikiWatershed/gwlf-e/issues/6#issuecomment-203970924

**Comment by mmcfarland** [comment]
Looks like a standard import will do what we want:
https://docs.python.org/2/faq/programming.html#how-do-i-share-global-variables-across-modules
