### ISSUE TITLE
Fix TravisCI build

### ISSUE THREAD

**Issue by kellyi** [WikiWatershed/gwlf-e#78]
Appears that the `master` and `develop` branches fail on Travis at this step:

> The command "pip install tox --use-mirrors" failed and exited with 2 during .

Fix that and also set Travis up to build both branches automatically once a month to help stay in touch with GWLF-E.

**Comment by rajadain** [comment]
These branches have been working correctly for the past few builds:

![image](https://user-images.githubusercontent.com/1430060/48025221-ca9fd980-e110-11e8-9635-a7cb47509f26.png)

Closing until this comes up again.
