### ISSUE TITLE
Optimize Dependency Specification

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/gwlf-e#83]
Currently, the new GWLF-E code (#81) specifies dependencies in both `requirements.txt` and `setup.py`. Figure out which is the preferred place, and how the dependencies should be specified, to make installation and use easier.

Ideally the user would just do `pip install gwlf-e` and all the right things would be installed automatically, without having to explicitly specify anything on the client side.

**Comment by rajadain** [comment]
Whoever works on this on the ops side, let me know so we can pair on it!

**Comment by hectcastro** [comment]
Updated plan is to ensure that a PR is opened for https://github.com/WikiWatershed/model-my-watershed/compare/tt/assimilate-drexel-gwlfe and reproduce that it works appropriately.

**Comment by rajadain** [comment]
I'm going to open that PR today so it is ready to review before pairing.

**Comment by rajadain** [comment]
PR is open https://github.com/WikiWatershed/model-my-watershed/pull/2902
